version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: mytestdb
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
